path:
  full_folder_path: test_data
  mask: access.log
json:
  save_folder_path: json_file
cron:
  state: true
  repeat_minutes: 1
postgresql:
  username: myusername
  password: password
  host_port: localhost
  db: mydb
